### ISSUE TITLE
Improving and Tweaking the Progress Bar

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/Airlift#13]
@arjunprakash027 

https://github.com/rsalmei/alive-progress#using-alive-progress

Right now, even if the our tool did not upload anything, Progress Bar reaches to 100%..

Hopefully, we can tweak and improve the Progress Bar at some stage.

**Comment by IAmVigneswaran** [comment]
@vzhd1701 Do you have any clue why would `tqdm` progress bar would "break" during upload?

Thank you.

**Comment by vzhd1701** [comment]
`tqdm` breaks only when something else is printing to `stdout` or `stderr` while it's drawing progress bar. You need to figure out why you are getting `airlift: error: the following arguments are required: --token, --base, --table` error in the middle of the upload.

**Comment by IAmVigneswaran** [comment]
> `tqdm` breaks only when something else is printing to `stdout` or `stderr` while it's drawing progress bar. You need to figure out why you are getting `airlift: error: the following arguments are required: --token, --base, --table` error in the middle of the upload.

@vzhd1701 Thanks for the insight!

**Comment by IAmVigneswaran** [comment]
@vzhd1701 Do you have any clue on why progress bar is breaking?  @arjunprakash027 Have been doing various trial and error on solving this. 

We have checked our shell scripts. There is no error in our .sh file.

<br>

<img width="684" alt="Progress Error" src="https://github.com/TheAcharya/Airlift/assets/118706051/6ae34bd9-b6b0-471a-bb85-4bf93d295f50">

**Comment by vzhd1701** [comment]
This one looks like a pyinstaller issue. Try adding [freeze_support](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) execution early on in the program.

**Comment by IAmVigneswaran** [comment]
> This one looks like a pyinstaller issue. Try adding [freeze_support](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) execution early on in the program.

Did you add this freeze support in csv2notion?

**Comment by vzhd1701** [comment]
No, I did not, but I remember something similar happening before in another project that used multiprocessing/multi-threading.

**Comment by IAmVigneswaran** [comment]
Thank you for insight!

**Comment by IAmVigneswaran** [comment]
> No, I did not, but I remember something similar happening before in another project that used multiprocessing/multi-threading.

Does that mean, csv2notion does not use multiprocessing/multi-threading.
