### ISSUE TITLE
Tweaking Time Format

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/Airlift#20]
@arjunprakash027 Right now the time is in `09/59/19.956408` this format.

Can we tweak the time format to be in this way `HH-MM-SS`  and round off the seconds?

Thank you.

**Comment by arjunprakash027** [comment]
Done!

**Comment by IAmVigneswaran** [comment]
I notice the date value is not added to the folder? Could the Time have “-” instead of “/" ?

**Comment by IAmVigneswaran** [comment]
Fixed.
