### ISSUE TITLE
Custom metavar class

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/Airlift#24]
@arjunprakash027 

Tweaking the `--help` layout to remove `..]`.

![tweak-help](https://github.com/TheAcharya/Airlift/assets/118706051/afb17c62-e2db-4443-9dac-0d24606e8860)

**Comment by arjunprakash027** [comment]
I found out that if i am using "nargs":"*" or "+", and i keep my metavar as "" or "\b", the help command is still showing the metavar for that argument as [ ..] and not an empty string "". Why is that and can it be solved in any way. I searched through the internet but in vain.
@vzhd1701

**Comment by vzhd1701** [comment]
I think that's because it's [generated that way by HelpFormatter](https://github.com/python/cpython/blob/9e56eedd018e1a4681789e634016cbb7699dcb8a/Lib/argparse.py#L600). You will need to override that part if you want to get rid of standard behavior like this:
```python
class CustomHelpFormatter(argparse.RawTextHelpFormatter):
    def _format_args(self, action, default_metavar):
        if action.nargs == argparse.ONE_OR_MORE:
            return ""
        return super()._format_args(action, default_metavar)


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        ...
        formatter_class=lambda prog: CustomHelpFormatter(
            prog, max_help_position=HELP_ARGS_WIDTH
        ),
    )
```

**Comment by arjunprakash027** [comment]
Thanks a lot @vzhd1701 , it works!
